### ISSUE TITLE
Item interactions? Help needed.

### ISSUE THREAD

**Issue by MisterShawn** [Sollace/CopperGolem#6]
I was wondering if you could explain what interactions are possible with the golems? Every item I tried resulting in nothing; pickaxe, shovel, shears, and hoe. I read the description on Modrinth and briefly looked at UseItemInteraction.java and it seems it basically takes whatever you give it and looks around for things to use it on.

I fenced the golem in, placed some cobblestone, then gave it a pickaxe. It just went around making the villager noise like it was trying to find something but couldn't. I made sure mob griefing was on. Still nothing. I tried the same with a sheep and shears, dirt and shovel, and matured wheat and hoe.

Maybe I'm missing something? Any help would be very much appreciated! Thank you!

**Comment by Sollace** [comment]
When you give it an item, the golem will look around trying to use it on blocks until it finds something that works. To speed up the process, you can also give it the item, then take nother of the same item yourself and break a block to instantly teach the golem that action.

Interacting with mobs isn't really implemented, so it's just with blocks for now.

**Comment by MisterShawn** [comment]
Thank you so much! Teaching the golem is what I was missing!

**Comment by Sollace** [comment]
No problem!

I'll also note that when you give it the item, what the golem is looking for are _right-click_ actions. Left-click actions are things you have to show it. :)

**Comment by JENOVAAbsolute** [comment]
I am on my testing world rn, and I threw together a simple cobble generator. I gave it a pickaxe, then used mine to break the cobble block quite a few times. As the other user stated, it just makes noises, rotates its head every time I break a block, and occasionally raise its arms in the air.

I also tried to get it to harvest wheat, but it just wanders around.

![2024-06-26_00 29 25](https://github.com/Sollace/CopperGolem/assets/60951301/4e6b53d8-f7f7-4fb0-8fce-0986c893145f)
![2024-06-26_00 36 54](https://github.com/Sollace/CopperGolem/assets/60951301/d0779a63-dfc6-4d74-a4d0-0609b2b195d5)

[latest.log](https://github.com/user-attachments/files/15982472/latest.log)
