### ISSUE TITLE
[BUG] Mobs won't use tools given to them.

### ISSUE THREAD

**Issue by JENOVAAbsolute** [Sollace/CopperGolem#7]
I threw together a cobble generator in a test world. I gave it a pickaxe, then used my own in an attempt to teach it what to do. The golem just makes noises constantly, rotates its head every time I break the block, and occasionally raise its arms in the air. It will not mine cobble.

I also tried to get it to harvest wheat, but it just wanders around even after I used the necessary tool to teach it.

[latest.log](https://github.com/user-attachments/files/15982472/latest.log)

![2024-06-26_00 29 25](https://github.com/Sollace/CopperGolem/assets/60951301/4e6b53d8-f7f7-4fb0-8fce-0986c893145f)
![2024-06-26_00 36 54](https://github.com/Sollace/CopperGolem/assets/60951301/d0779a63-dfc6-4d74-a4d0-0609b2b195d5)

**Comment by Sollace** [comment]
I'll mark this as a bug. They _should_ work in 1.21. Pretty sure I did test it in that version. Can't check right this moment though.

**Comment by Sollace** [comment]
They are working in 1.21. Gave one a pickaxe and mined some grass. he started mining every grass block around him.
